fix compatibility issue with NumPy>=2.4.0
When using recent NumPy, `nsec3hash.py` fails with:

                    sol = int(self.solutions[i])
                          ~~~^^^^^^^^^^^^^^^^^^^
    TypeError: only 0-dimensional arrays can be converted to Python scalars

This comes from a change from NumPy 2.4.0, documented in
https://numpy.org/devdocs/release/2.4.0-notes.html#raise-typeerror-on-attempt-to-convert-array-with-ndim-0-to-scalar

> Raise `TypeError` on attempt to convert array with `ndim > 0` to scalar
>
> Conversion of an array with `ndim > 0` to a scalar was deprecated in
> NumPy 1.25. Now, attempting to do so raises `TypeError`. Ensure you
> extract a single element from your array before performing this
> operation.

As `self.solutions` is a NumPy array with shape `(self.max_nholes, 1)`,
adding `[0]` fixes this issue. Add `[0]` in other places as well, to
make the code more robust to future NumPy changes.